Workspaces Part I
spkenv/spk pull request #1160
Opened 2024-12-17 22:49 UTC by rydrman

This PR is intended to be the first of a few related to #1121 

This first PR introduces the `spk-workspace` crate that defines the structure of a `workspace.spk.yaml` file and updates the various spk commands to recognize it. By default, a "virtual" workspace is created which collects all `*.spk.yaml` files in the current directory (this is in-line with previous behavior). The only new feature that becomes unlocked by this is that you can create a `workspace.spk.yaml` that collects files from additional or different paths. 

For example, this repository now has a workspace file that makes `spk build spk-convert-pip` work from anywhere within it, finding and building from the spec file under the packages folder.

2025-01-13 19:15 UTC, jrray requested changes

2025-01-13 19:15 UTC, jrray commented on crates/spk-workspace/src/file_test.rs
> +#[case("my-workspace", "other-dir")]
Is the repetition here intentional?

2025-01-13 22:24 UTC, rydrman commented on crates/spk-workspace/src/file_test.rs
> +#[case("my-workspace", "other-dir")]
ooops, ya probably not. I think I copy and pasted but never thought up another failure case to check...

2025-01-14 00:09 UTC, rydrman commented on crates/spk-workspace/src/file.rs
> +            match std::env::var("PWD").ok() {
ya, I can - it's to avoid the expansion in the case of error messages, ya

2025-01-14 18:36 UTC, jrray commented on crates/spk-workspace/src/file_test.rs
> +fn test_workspace_discovery(
```suggestion
#[rstest]
#[case("", "")]
#[case("my-workspace", "my-workspace/src/packages")]
#[should_panic]
#[case("my-workspace", "other-dir")]
#[should_panic]
#[case("my-workspace", "other-dir/src/packages")]
fn test_workspace_discovery(
```

2025-01-15 20:18 UTC, jrray approved these changes

2025-01-16 17:55 UTC, merged