Workspaces Part II
spkenv/spk pull request #1161
Opened 2024-12-18 21:35 UTC by rydrman

Builds on #1160 

Makes use of the versions specified for any given template file by parsing the version from the request and only `finding` spec files that are appropriate. Uses the `LeastSpecifiedVersionRange` to allow partial versions to be given.

As a practical example, the `workspace.spk.yaml` from this repository lists versions for each python spec, and so you can run `spk build python/3` to build the default version of the python 3 package spec.

2025-02-05 21:15 UTC, jrray requested changes

2025-02-05 21:15 UTC, jrray commented on crates/spk-workspace/src/error.rs
> +        "workspace not found, no {} in {0:?} or any parent",
I remember seeing guidance somewhere that errors should start with lowercase letters (so they compose nicely), here there is a mix. I would say we generally start our errors with uppercase, but could get on board with switching to lowercase. Either way we should pick one and stick with it as best we can.

2025-02-05 21:15 UTC, jrray commented on crates/spk-workspace/src/file.rs
> +    /// be produces, but rather that any can be attempted. It's also
```suggestion
    /// be produced, but rather that any can be attempted. It's also
```

2025-02-05 21:15 UTC, jrray commented on crates/spk-workspace/src/file_test.rs
> +#[case("my-workspace", "other-dir")]
Duplicate cases again.

2025-02-05 21:15 UTC, jrray commented on crates/spk-workspace/src/workspace.rs
> +// denoting unique error cases.
Wouldn't a `Result` type with a tailored `Error` enum fit this situation better?

2025-02-05 22:54 UTC, rydrman commented on crates/spk-workspace/src/error.rs
> +        "workspace not found, no {} in {0:?} or any parent",
ya I am bad for this, and I think it's because of python usually using uppercase - though maybe that's not even true. I think I agree that lowercase makes sense as a practice

2025-02-06 00:00 UTC, rydrman commented on crates/spk-workspace/src/builder.rs
> +    /// left as the defaults unless already set.
Ya, I think this is something that evolved over time and didn't get updated - it is based on the root if there is one

2025-02-06 01:23 UTC, rydrman commented on crates/spk-workspace/src/workspace.rs
> +// denoting unique error cases.
I tried this and the only challenge is that we cannot have `impl` for `Result` types and this type has functions on it - this is largely copied from the cli area so I didn't bother pushing too hard on a refactor in this change

Re: this comment, I actually managed to remove the lint error by returning references instead of owned values - so I will remove this block as well

2025-02-11 02:28 UTC, jrray approved these changes

2025-02-11 02:28 UTC, jrray commented on crates/spk-workspace/src/lib.rs
> +#![deny(missing_docs)]
Thank you! There was more missing documentation than I realized when asking for this.

2025-02-11 05:26 UTC, rydrman commented on crates/spk-workspace/src/lib.rs
> +#![deny(missing_docs)]
ya, there's some that felt a little redundant but 🤷🏻

2025-02-11 05:26 UTC, merged